import { accessSync, constants as fsConstants } from "node:fs";
import { join } from "node:path";
import type { Browser, BrowserContext, Route } from "playwright";
import { logger } from "./logger";
import { assertSafeUrl } from "./ssrf-guard";

/**
 * Last-resort page fetching with a real headless browser (Playwright).
 *
 * Reached only when plain HTTP extraction and embedded-JSON extraction both
 * failed (JS-rendered shells, bot-protection interstitials). The browser is a
 * lazily-launched singleton; if Playwright or Chromium is unavailable, this
 * degrades to `null` instead of breaking the API.
 *
 * Security: every HTTP(S) request generated by the page is preflight-checked
 * against the shared SSRF policy. Service workers and WebSockets are disabled
 * because they are unnecessary for article extraction and otherwise create
 * network paths that are harder to account for with request routing.
 *
 * Disable with WEB_FETCH_PLAYWRIGHT_FALLBACK=0.
 */

const BROWSER_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

/** Extra settle time for client-side hydration after DOMContentLoaded. */
const RENDER_SETTLE_MS = 2_000;

/** Resource types the extractor never needs. */
const BLOCKED_RESOURCE_TYPES = new Set(["image", "media", "font"]);

// ---------------------------------------------------------------------------
// Concurrency limiter (Chromium contexts are expensive on small hosts)
// ---------------------------------------------------------------------------

/** Max simultaneous browser page loads. Default 1; raise after load testing. */
const MAX_BROWSER_CONCURRENCY = (() => {
  const n = Number(process.env.PLAYWRIGHT_MAX_CONCURRENCY ?? "1");
  return Number.isFinite(n) && n >= 1 ? Math.floor(n) : 1;
})();

let activeBrowserJobs = 0;
const browserJobQueue: Array<() => void> = [];

async function acquireBrowserSlot(): Promise<void> {
  if (activeBrowserJobs >= MAX_BROWSER_CONCURRENCY) {
    await new Promise<void>((resolve) => browserJobQueue.push(resolve));
  }
  activeBrowserJobs++;
}

function releaseBrowserSlot(): void {
  activeBrowserJobs--;
  const next = browserJobQueue.shift();
  if (next) next();
}

// ---------------------------------------------------------------------------
// Browser-level network guard
// ---------------------------------------------------------------------------

/**
 * Validate a browser-generated request URL against the SSRF policy.
 *
 * Deliberately do not cache successful hostname/DNS verdicts here. A browser
 * performs its own DNS resolution after route continuation, so re-resolving
 * on each routed request narrows the DNS-rebinding/TOCTOU window and prevents
 * one earlier safe request from blessing later URLs on the same hostname.
 */
export async function isSafeBrowserRequestUrl(rawUrl: string): Promise<boolean> {
  let url: URL;
  try {
    url = new URL(rawUrl);
  } catch {
    return false;
  }

  // Internal, non-network document URLs do not open a socket themselves.
  if (url.protocol === "about:" || url.protocol === "data:" || url.protocol === "blob:") {
    return true;
  }
  if (url.protocol !== "http:" && url.protocol !== "https:") return false;

  // Check credentials before DNS work. This must never be hidden behind a
  // hostname-only cache because credentials are properties of the full URL.
  if (url.username || url.password) return false;

  try {
    await assertSafeUrl(rawUrl);
    return true;
  } catch {
    return false;
  }
}

/** Attach interception before any page is created. */
async function installRequestGuard(context: BrowserContext): Promise<void> {
  await context.route("**/*", async (route: Route) => {
    const request = route.request();
    if (BLOCKED_RESOURCE_TYPES.has(request.resourceType())) {
      await route.abort("blockedbyclient");
      return;
    }
    if (await isSafeBrowserRequestUrl(request.url())) {
      await route.continue();
      return;
    }
    logger.warn({ url: request.url() }, "Blocked browser request (SSRF guard)");
    await route.abort("blockedbyclient");
  });

  // Page extraction never needs a persistent socket. Blocking all WebSockets
  // prevents ws:// / wss:// from becoming a second, unvalidated network path.
  await context.routeWebSocket("**/*", async (socket) => {
    logger.debug({ url: socket.url() }, "Blocked browser WebSocket");
    await socket.close({ code: 1008, reason: "Network policy" });
  });
}

// ---------------------------------------------------------------------------
// Shared browser lifecycle
// ---------------------------------------------------------------------------

let browserPromise: Promise<Browser> | null = null;

/**
 * Prefer an operator-supplied Chromium path, then discover a system Chromium
 * from PATH. This lets Replit use its reproducible Nix Chromium without
 * downloading a separate Playwright browser bundle. Other hosts continue to
 * fall back to Playwright's managed executable when no system browser exists.
 */
export function resolveSystemChromiumExecutable(
  env: NodeJS.ProcessEnv = process.env,
): string | null {
  const explicit = env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?.trim();
  if (explicit) {
    try {
      accessSync(explicit, fsConstants.X_OK);
      return explicit;
    } catch {
      logger.warn({ executablePath: explicit }, "Configured Chromium executable is unavailable");
    }
  }

  const pathEntries = (env.PATH ?? "").split(":").filter(Boolean);
  const names = ["chromium", "chromium-browser", "google-chrome-stable", "google-chrome"];
  for (const directory of pathEntries) {
    for (const name of names) {
      const candidate = join(directory, name);
      try {
        accessSync(candidate, fsConstants.X_OK);
        return candidate;
      } catch {
        // Continue searching PATH.
      }
    }
  }
  return null;
}

async function launchBrowser(): Promise<Browser> {
  const { chromium } = await import("playwright");
  const executablePath = resolveSystemChromiumExecutable();
  const browser = await chromium.launch({
    headless: true,
    ...(executablePath ? { executablePath } : {}),
  });
  logger.info(
    { browserSource: executablePath ? "system" : "playwright", executablePath: executablePath ?? undefined },
    "Headless Chromium launched",
  );
  browser.on("disconnected", () => {
    browserPromise = null;
  });
  return browser;
}

function getBrowser(): Promise<Browser> {
  if (!browserPromise) {
    browserPromise = launchBrowser();
    browserPromise.catch(() => {
      browserPromise = null;
    });
  }
  return browserPromise;
}

function discardBrowser(): void {
  const pending = browserPromise;
  browserPromise = null;
  pending?.then((b) => b.close()).catch(() => undefined);
}

async function createContext(): Promise<BrowserContext> {
  let lastErr: unknown;
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const browser = await getBrowser();
      return await browser.newContext({
        userAgent: BROWSER_UA,
        locale: "ja-JP",
        viewport: { width: 1280, height: 800 },
        // Playwright documents that context.route() cannot reliably account
        // for page requests handled by a Service Worker. Block registration so
        // every network request stays on the routed path above.
        serviceWorkers: "block",
      });
    } catch (err) {
      lastErr = err;
      logger.warn({ err, attempt }, "Browser context creation failed; resetting browser");
      discardBrowser();
    }
  }
  throw lastErr;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export async function fetchWithBrowser(
  url: string,
  timeoutMs: number,
): Promise<{ title: string; text: string } | null> {
  await acquireBrowserSlot();
  try {
    let context: BrowserContext;
    try {
      context = await createContext();
    } catch (err) {
      logger.warn(
        { err },
        "Playwright browser unavailable; skipping browser fallback",
      );
      return null;
    }

    try {
      await installRequestGuard(context);
      const page = await context.newPage();
      const response = await page.goto(url, {
        waitUntil: "domcontentloaded",
        timeout: timeoutMs,
      });
      if (!response || !response.ok()) {
        logger.warn({ url, status: response?.status() }, "Browser fetch rejected");
        return null;
      }
      await page
        .waitForLoadState("networkidle", { timeout: RENDER_SETTLE_MS })
        .catch(() => undefined);

      const { title, articleText, bodyText } = await page.evaluate(() => {
        const doc = (globalThis as Record<string, unknown>).document as {
          title: string;
          querySelector(selector: string): { innerText?: string } | null;
          body?: { innerText?: string } | null;
        };
        const semantic = doc.querySelector("article") ?? doc.querySelector("main");
        return {
          title: doc.title,
          articleText: semantic?.innerText?.trim() ?? "",
          bodyText: doc.body?.innerText?.trim() ?? "",
        };
      });
      const text = articleText.length >= 200 ? articleText : bodyText;
      if (text.length === 0) return null;
      return { title: title || url, text };
    } catch (err) {
      logger.warn({ err, url }, "Browser fetch failed");
      return null;
    } finally {
      await context.close().catch(() => undefined);
    }
  } finally {
    releaseBrowserSlot();
  }
}

/** Close the shared browser. Exported for tests and graceful shutdown. */
export async function closeBrowser(): Promise<void> {
  if (!browserPromise) return;
  const pending = browserPromise;
  browserPromise = null;
  await pending.then((b) => b.close()).catch(() => undefined);
}
