import { index, integer, pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

import { conversations } from "./conversations";
import { messages } from "./messages";

/**
 * Binary assets generated by the assistant (PDF, Office files, etc.) within a
 * chat session. Stored in PostgreSQL bytea for the minimal setup; the schema
 * keeps a storage-kind abstraction so migration to object storage later only
 * requires adding a `storageKey` column and a small adapter.
 */
export const assets = pgTable(
  "assets",
  {
    id: serial("id").primaryKey(),
    conversationId: integer("conversation_id")
      .notNull()
      .references(() => conversations.id, { onDelete: "cascade" }),
    messageId: integer("message_id").references(() => messages.id, {
      onDelete: "set null",
    }),
    filename: text("filename").notNull(),
    mimeType: text("mime_type").notNull(),
    /** File size in bytes. */
    size: integer("size").notNull(),
    /** Base64-encoded file bytes. Kept in text because this Drizzle version lacks a bytea helper. */
    data: text("data").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("assets_conversation_id_idx").on(table.conversationId),
    index("assets_message_id_idx").on(table.messageId),
  ],
);

export const insertAssetSchema = createInsertSchema(assets).omit({
  id: true,
  createdAt: true,
});

export type Asset = typeof assets.$inferSelect;
export type InsertAsset = z.infer<typeof insertAssetSchema>;
